services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"

  python-app:
    build: .
    ports:
      - "5001:5000"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: devpass
    volumes:
        - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: