name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Python app
        run: python -m py_compile app.py

      - name: Run tests
        run: pytest -v

      - name: Security scan
        run: bandit -r . -c .bandit

      - name: Dependency vulnerability scan
        run: pip-audit

      - name: Build Docker image
        run: docker build -t devsecops-journey-python-app:${{ github.sha }} .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "devsecops-journey-python-app:${{ github.sha }}"
          format: "table"
          severity: "CRITICAL,HIGH,MEDIUM,LOW"
          exit-code: "0"

      - name: Log in to GHCR
        if: github.even_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GHCR
          if: github.even_name == 'push' && github.ref == 'refs/heads/main'
          run:
            docker tag devsecopss-journey-python-app:${{ github.sha }} ghcr.io/${{ github.repository }}:${{ github.sha }

            docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

            